// <auto-generated />
using System;
using CoderNexues.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoderNexues.Migrations
{
    [DbContext(typeof(CN_DbContext))]
    [Migration("20260107080128_AddAnnouncements")]
    partial class AddAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoderNexues.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementID"));

                    b.Property<int>("CampID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnnouncementID");

                    b.HasIndex("CampID");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("CoderNexues.Models.C_Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("CampID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("CampID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CoderNexues.Models.Camp", b =>
                {
                    b.Property<int>("CampID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampID"));

                    b.Property<string>("CampName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampID");

                    b.ToTable("Camps");
                });

            modelBuilder.Entity("CoderNexues.Models.CampUser", b =>
                {
                    b.Property<int>("CampUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampUserID"));

                    b.Property<int>("CampID")
                        .HasColumnType("int");

                    b.Property<string>("RoleInCamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CampUserID");

                    b.HasIndex("CampID");

                    b.HasIndex("UserID");

                    b.ToTable("CampUsers");
                });

            modelBuilder.Entity("CoderNexues.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionID")
                        .HasColumnType("int");

                    b.HasKey("EvaluationID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("EvaluatorID");

                    b.HasIndex("SubmissionID")
                        .IsUnique();

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("CoderNexues.Models.FeedbackCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("FeedbackCategories");
                });

            modelBuilder.Entity("CoderNexues.Models.StudentPerformance", b =>
                {
                    b.Property<int>("PerformanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformanceID"));

                    b.Property<decimal>("AvgScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CampID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PerformanceID");

                    b.HasIndex("CampID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentPerformances");
                });

            modelBuilder.Entity("CoderNexues.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionID"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.HasKey("SubmissionID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TaskID");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("CoderNexues.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoderNexues.Models.Announcement", b =>
                {
                    b.HasOne("CoderNexues.Models.Camp", "Camp")
                        .WithMany("Announcements")
                        .HasForeignKey("CampID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camp");
                });

            modelBuilder.Entity("CoderNexues.Models.C_Task", b =>
                {
                    b.HasOne("CoderNexues.Models.Camp", "Camp")
                        .WithMany("Tasks")
                        .HasForeignKey("CampID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camp");
                });

            modelBuilder.Entity("CoderNexues.Models.CampUser", b =>
                {
                    b.HasOne("CoderNexues.Models.Camp", "Camp")
                        .WithMany("CampUsers")
                        .HasForeignKey("CampID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoderNexues.Models.User", "User")
                        .WithMany("CampUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoderNexues.Models.Evaluation", b =>
                {
                    b.HasOne("CoderNexues.Models.FeedbackCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoderNexues.Models.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoderNexues.Models.Submission", "Submission")
                        .WithOne("Evaluation")
                        .HasForeignKey("CoderNexues.Models.Evaluation", "SubmissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Evaluator");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CoderNexues.Models.StudentPerformance", b =>
                {
                    b.HasOne("CoderNexues.Models.Camp", "Camp")
                        .WithMany()
                        .HasForeignKey("CampID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoderNexues.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoderNexues.Models.Submission", b =>
                {
                    b.HasOne("CoderNexues.Models.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoderNexues.Models.C_Task", "Task")
                        .WithMany("Submissions")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CoderNexues.Models.C_Task", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("CoderNexues.Models.Camp", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("CampUsers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CoderNexues.Models.Submission", b =>
                {
                    b.Navigation("Evaluation")
                        .IsRequired();
                });

            modelBuilder.Entity("CoderNexues.Models.User", b =>
                {
                    b.Navigation("CampUsers");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
